config/routes.rb
Rails.application.routes.draw do
  get 'recipes/index'

  root 'recipes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
require 'httparty'

class Recipe
  include HTTParty

  key_value = ENV['FOOD2FORK_KEY']
  hostport = ENV['FOOD2FORK_SERVER_AND_PORT'] || 'www.food2fork.com'
  base_uri "http://#{hostport}/api"
  default_params key: key_value
  format :json

  def self.for (keyword)
    get("/search", query: {q: keyword})["recipes"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @search_term = params[:looking_for] || 'diet'
    @recipes = Recipe.for(@search_term)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPractice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<div class="container">
<div class="row">
    <div class="col-lg-12">
    <div>
        <h2>Search for a recipe today!</h2>
        <p>Search up your favorite recipe, just put input the ingredients you want in it(commas between ingredients!) and voila!</p>
    </div>
    <div class="search container">
        <%= form_tag recipes_index_path, method: :get, id: 'search' do %>
            <%= label_tag :ingredient %>
            <%= text_field_tag :search , '', placeholder: 'Enter what you\' hungry for' , :required => true %>
            <%= submit_tag "Search", class: 'btn btn-success' %>
        <% end %>
    </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <h3>Searching Recipe for - <%= @search_term %></h3>

        <table border="1">
        <tr>
            <th>Image</th>
            <th>Name</th>
            <th>Social Rank</th>
        </tr>
        <% @recipes.each do |recipe| %>
            <tr class=<%= cycle('even', 'odd') %>>
            <td><%= image_tag(recipe["image_url"])%></td>
            <td><%= recipe["title"] %></td>
            <td><%= recipe["social_rank"] %></td>
            </tr>
        <% end %>
        </table>
    </div>
</div>
<div>